kind: Pod
apiVersion: v1
metadata:
  name: liveness-pod
  labels:
    app: lns
spec:
  containers:
  - name: liveness
    image: busybox
    args:
    - /bin/sh                       # Use the sh shell
    - -c                            # With the '-c' flag (commands to follow)
    - touch /liveness; sleep 6000   # Create a file, then sleep
    # Define a liveness probe for the container
    livenessProbe:
      exec:
        command:
        - cat                       # Read a file's content
        - /liveness                 # The file to read
      initialDelaySeconds: 5        # Delay before starting the liveness probe (in seconds)
      periodSeconds: 5              # Time between consecutive liveness probes (in seconds)
