# Introduction:
# This YAML file defines a Deployment for an Nginx application within a Kubernetes cluster. The Deployment will ensure
# that a specified number of replica Pods are maintained, each running the Nginx container. This setup is ideal for 
# hosting a static website or as a reverse proxy server.

apiVersion: apps/v1  # Specifies the API version to use
kind: Deployment     # Indicates that this is a Deployment resource
metadata:
  name: nginx-deployment # Names the Deployment
  labels:
    app: nginx      # Label for categorizing the Deployment

spec:
  replicas: 2       # Desired number of pod replicas
  selector:
    matchLabels:
      app: nginx    # Identifies the set of pods to manage using their labels

  template:         # Defines the pod blueprint
    metadata:
      labels:
        app: nginx  # Labels for the pods created from this template
    spec:
      containers:
      - name: nginx # Container name
        image: nginx:1.12  # Specifies the container image and version
        ports:
        - containerPort: 80  # Port to expose on the container

# Conclusion:
# This Deployment ensures that two Pods running the Nginx 1.12 version are always available. By labeling these Pods with 
# "app=nginx", it’s easy to manage and scale the application as necessary. Ports 80 are exposed to allow HTTP traffic to the Nginx server.
