# This YAML file is used to create a Deployment resource in Kubernetes.
# Deployment ensures that a specified number of pod replicas are running at any given time.

apiVersion: apps/v1  # Specifies the API version to use
kind: Deployment     # Indicates that this is a Deployment resource
metadata:
  name: nginx-deployment # Names the Deployment
  labels:
    app: nginx      # Label for categorizing the Deployment

spec:
  replicas: 2       # Desired number of pod replicas
  selector:
    matchLabels:
      app: nginx    # Identifies the set of pods to manage using their labels

  template:         # Defines the pod blueprint
    metadata:
      labels:
        app: nginx  # Labels for the pods created from this template
    spec:
      containers:
      - name: nginx # Container name
        image: nginx:1.12  # Specifies the container image and version
        ports:
        - containerPort: 80  # Port to expose on the container


# This Deployment will ensure that 2 replicas of Pods running the nginx:1.12 image are always running.
# The Pods will be selected and managed by this Deployment based on the "app=nginx" label.
