kind: Service
apiVersion: v1
metadata:
  name: readiness-svc      # Name of the Service
spec:
  selector:
    app: rns               # Select Pods with label app=rns
  ports:
    - protocol: "TCP"      # Protocol for the port (TCP in this case)
      port: 80             # Port exposed by the Service
      targetPort: 80       # Target port on the Pods to forward traffic to
